# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: D:\Python WDR\wdr-ddj-cloud\scraper_template
contact_email: nandor@hulverscheidt.com
contact_name: Nandor
description: Jannes ist schuld.
display_name: Testscrape_WDR_DDJ_Nandor
ephemeral_storage: '512'
interval: 15min
interval_custom: null
memory_size: '512'
module_name: testscrape_wdr_ddj_nandor
preset: pandas

