# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: C:\Users\Elena\Documents\scraping_test_jannes\wdr-ddj-cloud\scraper_template
contact_email: elena.riedlinger@wdr.de
contact_name: elena
description: 'elenas test scraper

    '
display_name: firsttry_elena
ephemeral_storage: '512'
interval: daily
interval_custom: null
memory_size: '1024'
module_name: firsttry_elena
preset: pandas

