# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: /home/jhoeke/git/ddj/wdr-ddj-cloud/scraper_template
contact_email: mail@jhoeke.de
contact_name: Jannes Höke
description: 'Port des LANUK Scrapers aus der pegelstaende-pipeline-nrw, um kurz-
    und mittelfristig eine Datawrapper-Karte zu befüllen '
display_name: LANUK Pegelstände Karte
ephemeral_storage: '512'
interval: custom
interval_custom: rate(30 minutes)
memory_size: '1024'
module_name: lanuk_karte
preset: minimal

